### ISSUE TITLE
Running sbt runAll is giving errors 

### ISSUE THREAD

**Issue by fortm** [lagom/online-auction-java#156]
I ran sbt runAll after installing ElasticSearch locally on Windows 10 and get all these errors. 
The UI would open on 9000 but with these errors. Also , logout button gives the error.

**Do we need to customize some variables in addition to running sbt runAll locally ?**

Errors -> Gettings these exceptions from kafka

```
15:05:49.601 [error] com.lightbend.lagom.internal.broker.kafka.KafkaSubscriberActor [sourceThread=transactionImpl-application-akka.actor.default-dispatcher-17, akkaTimestamp=09:35:49.598UTC, akkaSource=akka.tcp://transactionImpl-application@127.0.0.1:57178/user/KafkaBackoffConsumer1-item-ItemEvent/KafkaConsumerActor1-item-ItemEvent, sourceActorSystem=transactionImpl-application] - Topic subscription interrupted due to failure: [java.lang.Exception: Consumer actor terminated]
15:05:49.602 [error] akka.actor.OneForOneStrategy [sourceThread=transactionImpl-application-akka.actor.default-dispatcher-18, akkaTimestamp=09:35:49.598UTC, akkaSource=akka://transactionImpl-application/user/KafkaBackoffConsumer1-item-ItemEvent/KafkaConsumerActor1-item-ItemEvent, sourceActorSystem=transactionImpl-application] - Consumer actor terminated
java.lang.Exception: Consumer actor terminated
        at akka.kafka.internal.SingleSourceLogic$$anonfun$preStart$1.apply(SingleSourceLogic.scala:54)
        at akka.kafka.internal.SingleSourceLogic$$anonfun$preStart$1.apply(SingleSourceLogic.scala:40)
        at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:166)
        at akka.stream.stage.GraphStageLogic$StageActor$$anonfun$1.apply(GraphStage.scala:133)
        at akka.stream.stage.GraphStageLogic$StageActor$$anonfun$1.apply(GraphStage.scala:133)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Timeout warnings-> Hundreds of them in log

`15:06:15.676 [warn] akka.kafka.KafkaConsumerActor [sourceThread=searchImpl-application-akka.kafka.default-dispatcher-60, akkaTimestamp=09:36:15.676UTC, akkaSource=akka://searchImpl-application/system/kafka-consumer-8, sourceActorSystem=searchImpl-application] - Consumer interrupted with WakeupException after timeout. Message: null. Current value of akka.kafka.consumer.wakeup-timeout is 3000 milliseconds
`

(edited: this is a separate issue we'll track in #157 )
/logout -> On logout from localhost:9000, gives these errors

```
Execution exception
[CompletionException: java.lang.RuntimeException: There is no HTTP Context available from here.]

```

**Comment by ignasi35** [comment]
Hi @fortm thanks for reporting this. 

I think there are two unrelated issues to solve. I've created #157 to track the error when using `logout` and I'll rename this issue to track the errors on consuming from Kafka in the `SearchService`.

**Comment by ignasi35** [comment]
After reviewing the stacktrace you copied:

```
15:05:49.601 [error] com.lightbend.lagom.internal.broker.kafka.KafkaSubscriberActor [sourceThread=transactionImpl-application-akka.actor.default-dispatcher-17, akkaTimestamp=09:35:49.598UTC, akkaSource=akka.tcp://transactionImpl-application@127.0.0.1:57178/user/KafkaBackoffConsumer1-item-ItemEvent/KafkaConsumerActor1-item-ItemEvent, sourceActorSystem=transactionImpl-application] - Topic subscription interrupted due to failure: [java.lang.Exception: Consumer actor terminated]
15:05:49.602 [error] akka.actor.OneForOneStrategy [sourceThread=transactionImpl-application-akka.actor.default-dispatcher-18, akkaTimestamp=09:35:49.598UTC, akkaSource=akka://transactionImpl-application/user/KafkaBackoffConsumer1-item-ItemEvent/KafkaConsumerActor1-item-ItemEvent, sourceActorSystem=transactionImpl-application] - Consumer actor terminated
java.lang.Exception: Consumer actor terminated
        at akka.kafka.internal.SingleSourceLogic$$anonfun$preStart$1.apply(SingleSourceLogic.scala:54)
        at akka.kafka.internal.SingleSourceLogic$$anonfun$preStart$1.apply(SingleSourceLogic.scala:40)
```

I see the error happens on `[sourceThread=transactionImpl-application-akka.actor.default-dispatcher-18...` so that's the `TransactionService`. The `TransactionService` doesn't use `elastic-search` so I don't think the problem is related to elastic-search at all.

Are all the errors you see in the logs happening in the `TransactionService` ? is is possible that all services fail to connect to Kakfa? If that is the case you would see that errors happen in different threads ( `[sourceThread=transactionImpl-application...`)  and that would mean your embedded Kafka (started by `sbt runAll`)  is unreachable for some other reason (internal proxy, windows firewall, corrupted storage from previous runs, ...).

Could you try deleting your `target/` folder in the root of the `online-auction-java` project and try again?

Thanks!

**Comment by fortm** [comment]
@ignasi35 I was indeed behind a VPN when the above errors come. Last time I got error on biddingImpl-application-akka.actor.default-dispatcher-16 , so it is different than transactionImpl-application-akka.actor.default-dispatcher-18. 

When I leave VPN, the error goes away. Also those WakeupException  stops coming after a while when not behind VPN

Can you please help me understand how can we run application behind VPN ?

**Comment by ignasi35** [comment]
When running Lagom in Development Mode (`sbt runAll`) the plugin starts 3 processes: Cassandra, Kafka and a JVM with all lagom-specific components. In total you are opening 1 port per service + 4 ports (cassandra, kafka, service locator and service gateway).

All services, kafka and cassandra are registered in the service locator so that clients can discover the `host:port` where each service is sitting. You should make sure those `host:port` pairs are not redirected into the VPN. You can have a look at the various available services on the `http://localhost:8000/service` URI when running Lagom in Development Mode.

**Comment by TimMoore** [comment]
Assuming this is no longer an issue. Please comment if you're still having problems @fortm.
