### ISSUE TITLE
TransportException on home page

### ISSUE THREAD

**Issue by fortm** [lagom/online-auction-java#159]
I have run sbt clean runAll because without clearing target folder, kafka will error out with message - kafka stopped unexpectedly.

But since then getting below error on opening localhost:9000 -> 

```
[CompletionException: com.lightbend.lagom.javadsl.api.transport.TransportException: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at com.example.auction.user.impl.Mappers.toApi(Mappers.java:11)
	at com.example.auction.user.impl.UserServiceImpl.lambda$null$2(UserServiceImpl.java:55)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 (TransportErrorCode{http=500, webSocket=1011, description='Unexpected Condition'})]
```

**Comment by fortm** [comment]
However , on restart of machine, error seems to be not coming. I assume it was some corrupted data. 

In production, I am considering to use the lagom project with kubernetes without conductR. I believe there won't be so many instances of corrupted data in production. These corruptions must be happening due to embedded cassandra and kafka most likely.

**Comment by ignasi35** [comment]
Hi @fortm I also think that's the case.

The embedded Kafka (and ZooKeeper) sometimes fail to flush their state consistently when shutting down. In production, ZK and Kafka rarely see a shutdown and when they do it should be dealt with carefully to ensure the restored service is operating as expected before it's made locatable.

I will close this issue. There is further information on https://github.com/lagom/lagom/issues/382

Thanks for reporting!
