### ISSUE TITLE
Nav controller initialization failure in some locales

### ISSUE THREAD

**Issue by chang-chao** [lagom/online-auction-java#161]
The initialization code below in webGateway/controllers/Nav.java will fail for some locales( for example:JAPANESE)

<pre>
    private static final PrettyTime prettyTime = new PrettyTime();
    static {
        prettyTime.removeUnit(JustNow.class);
        ResourcesTimeUnit justNow = new ResourcesTimeUnit() {
            {
                setMaxQuantity(10000);
            }
            @Override
            protected String getResourceKeyPrefix() {
                return "JustNow";
            }
        };
        prettyTime.registerUnit(justNow, new ResourcesTimeFormat(justNow));
    }
</pre>

to reproduce it ,we can just change the first line to 
<pre>
PrettyTime prettyTime = new PrettyTime(Locale.JAPAN);
</pre>

It will fail with the following exception:
<pre>
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle org.ocpsoft.prettytime.i18n.Resources, key Pattern
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.ocpsoft.prettytime.i18n.Resources_ja$JaTimeFormat.<init>(Resources_ja.java:148)
	at org.ocpsoft.prettytime.i18n.Resources_ja.getFormatFor(Resources_ja.java:117)
	at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:34)
	at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:16)
	at org.ocpsoft.prettytime.PrettyTime.registerUnit(PrettyTime.java:472)
</pre>

this is because the getUnitName(TimeUnit) method of JaTimeFormat class cannot properly get the unit name in case of anonymous TimeUnit class(An empty string is returned).

<pre>
        private String getUnitName(TimeUnit unit) {
            return unit.getClass().getSimpleName();
        }
</pre>

**Comment by chang-chao** [comment]
Possibility it is an issue of PrettyTime,instead of this project.
