### ISSUE TITLE
sbt runAll raise errro  Unknown CF 

### ISSUE THREAD

**Issue by skanel** [lagom/online-auction-java#165]
```
[info] Starting Cassandra
....................Exception (java.lang.IllegalArgumentException) encountered during startup: Unknown CF 523d0430-189e-11e8-bb8e-799e790a6720
java.lang.IllegalArgumentException: Unknown CF 523d0430-189e-11e8-bb8e-799e790a6720
	at org.apache.cassandra.db.Keyspace.getColumnFamilyStore(Keyspace.java:204)
	at org.apache.cassandra.db.view.ViewManager.addView(ViewManager.java:152)
	at org.apache.cassandra.db.view.ViewManager.reload(ViewManager.java:125)
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:324)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:127)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:104)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:293)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:735)
02/23 22:24:46 ERROR[main] o.a.c.s.CassandraDaemon - Exception encountered during startup
java.lang.IllegalArgumentException: Unknown CF 523d0430-189e-11e8-bb8e-799e790a6720
	at org.apache.cassandra.db.Keyspace.getColumnFamilyStore(Keyspace.java:204) ~[cassandra-bundle.jar:0.52-SNAPSHOT]
	at org.apache.cassandra.db.view.ViewManager.addView(ViewManager.java:152) ~[cassandra-bundle.jar:0.52-SNAPSHOT]
	at org.apache.cassandra.db.view.ViewManager.reload(ViewManager.jav
```

**Comment by yg-apaza** [comment]
Try doing `sbt clean` and then run `sbt runAll` again
