### ISSUE TITLE
ServiceLocator is not bound

### ISSUE THREAD

**Issue by maarek** [lagom/online-auction-java#96]
I pulled down the project and tried to runAll but I just get into a loop of not being able to locate Cassandra.

```
[warn] c.l.l.i.p.c.ServiceLocatorSessionProvider - Could not find Cassandra contact points, due to: ServiceLocator is not bound
[warn] a.p.c.j.CassandraJournal - Failed to connect to Cassandra and initialize. It will be retried on demand. Caused by: ServiceLocator is not bound
```

```
[error] a.a.OneForOneStrategy - Ask timed out on [Actor[akka://transactionImpl-application/user/cassandraOffsetStorePrepare-singleton/singleton/cassandraOffsetStorePrepare#-352900502]] after [20000 ms]. Sender[Actor[akka://transactionImpl-application/user/cassandraOffsetStorePrepare-singleton/singleton/cassandraOffsetStorePrepare#-352900502]] sent message of type "com.lightbend.lagom.internal.persistence.cluster.ClusterStartupTaskActor$Execute$".
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://transactionImpl-application/user/cassandraOffsetStorePrepare-singleton/singleton/cassandraOffsetStorePrepare#-352900502]] after [20000 ms]. Sender[Actor[akka://transactionImpl-application/user/cassandraOffsetStorePrepare-singleton/singleton/cassandraOffsetStorePrepare#-352900502]] sent message of type "com.lightbend.lagom.internal.persistence.cluster.ClusterStartupTaskActor$Execute$".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126) ~[akka-actor_2.11-2.4.17.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[scala-library-2.11.8.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284) ~[akka-actor_2.11-2.4.17.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236) ~[akka-actor_2.11-2.4.17.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

```

```
localhost:8000/services

[{"name":"cas_native","url":"tcp://127.0.0.1:4000/cas_native"},{"name":"kafka_native","url":"tcp://localhost:9092/kafka_native"},{"name":"elastic-search","url":"http://127.0.0.1:9200"}]
```

**Comment by ignasi35** [comment]
Hi @maarek, here's some reasons why the error appeared:

 - cassandra did not start properly
 - there's a PROXY resolution setup on you OS causing the connection to `"tcp://127.0.0.1:4000/cas_native"` to be resent to some other IP/PROXY/GW which blocks the port or doesn't complete the redirection
 - other ?

Are you able to reproduce the issue on every invocation?
You can check if cassandra is running by using the `jps` command from a terminal. This is part of the HotSpot JVM (Oracle's JVM) so if you are using OpenJDK it may not be available. It's a `ps aux` equivalent only listing jvm processes.
If `CassandraLauncher` is listed you can also try to connect to it using a cassandra client ([dbeaver](http://dbeaver.jkiss.org/) or [devcenter](https://docs.datastax.com/en/developer/devcenter/doc/devcenter/dcInstallation.html) )

**Comment by maarek** [comment]
@ignasi35 Ah, thanks. It's quite possibly a proxy issue. I am trying to test now to see if that is the case.

**Comment by TimMoore** [comment]
@maarek did you ever have any luck?

**Comment by ignasi35** [comment]
Haven't heard in a while. Will close.
